#include<bits/stdc++.h>
#define Max 2

///中国方块 Chinese Square  By:Hire or Fire

using namespace std;
int cnt=0;///分数
int fl;///方块类型
int yl=0;///旋转类型
int flag0=0;///判断是否该创造下一个方块
int flag=0;///判断游戏是否结束
int markl,markr;///当前位置
char c;///指令
int map0[10][10]={
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0};
void print()///打印游戏画面
{
    for(int i=0;i<10;i++)
    {
        for(int j=0;j<10;j++)
        {
            if(map0[i][j]==0) cout<<"▇";
            else cout<<"  ";
        }
        cout<<endl;
    }
    cout<<"---------------------------------------------------------------------"<<endl;
    cout<<"你的得分是："<<cnt<<"                   "<<"祝小徐生日牛逼，永远快乐"<<endl;
    cout<<"w a s d 控制方向，y 控制旋转。上下左右都可以消除，尽量选择左边和上边"<<endl;
    cout<<"消除把，右边和上边有一些问题，我不知道我的代码抽风了还是咋。"<<endl;
    cout<<"还有就是最外面一圈尽量别放砖块，避免出现不必要的bug，只需要堆满一行的中间八个方格就能消除得分了。"<<endl;
}
void creat()///创造方块
{
    markl=4;
    markr=4;
    fl=rand()%5+1;
    if(fl==1)
    {
        if(map0[markl][markr]>0||map0[markl+1][markr+1]>0||map0[markl+1][markr]>0||map0[markl][markr+1]>0||((map0[markl-1][markr]>0||map0[markl-1][markr+1]>0)&&
        (map0[markl][markr-1]>0||map0[markl+1][markr-1]>0)&&(map0[markl+2][markr]>0||map0[markl+2][markr+1]>0)&&(map0[markl][markr+2]>0||map0[markl+1][markr+2]>0)))
        {
            flag=1;
        }
        else
        {
            map0[markl][markr]=1;
            map0[markl+1][markr+1]=1;
            map0[markl+1][markr]=1;
            map0[markl][markr+1]=1;
        }
    }
    if(fl==2)
    {
        if(map0[markl][markr]>0||map0[markl+1][markr]>0||map0[markl][markr+1]>0||((map0[markl][markr+2]>0||map0[markl+1][markr+1]>0)&&
        (map0[markl-1][markr]>0||map0[markl-1][markr+1]>0)&&(map0[markl][markr-1]>0||map0[markl+1][markr-1]>0)&&(map0[markl+2][markr]>0||map0[markl+1][markr+1]>0)))
        {
            flag=1;
        }
        else
        {
            map0[markl][markr]=1;
            map0[markl+1][markr]=1;
            map0[markl][markr+1]=1;
        }
    }
    if(fl==3)
    {
        if(map0[markl][markr]>0||map0[markl-1][markr]>0||map0[markl+1][markr]>0||((map0[markl+1][markr-1]>0||map0[markl-1][markr-1]>0||map0[markl][markr-1]>0)&&
        (map0[markl+2][markr]>0)&&(map0[markl+1][markr+1]>0||map0[markl-1][markr+1]>0||map0[markl][markr+1]>0)&&(map0[markl-2][markr]>0)))
        {
            flag=1;
        }
        else
        {
            map0[markl][markr]=1;
            map0[markl-1][markr]=1;
            map0[markl+1][markr]=1;
        }
    }
    if(fl==4)
    {
        if(map0[markl][markr]>0||map0[markl][markr+1]>0||map0[markl+1][markr]>0||map0[markl+2][markr]>0||((map0[markl-1][markr]>0||map0[markl-1][markr+1]>0)&&
        (map0[markl][markr-1]>0||map0[markl+1][markr-1]>0||map0[markl+2][markr-1]>0)&&(map0[markl+3][markr]>0||map0[markl+1][markr+1]>0)&&(map0[markl][markr+2]>0||map0[markl+1][markr+1]>0||map0[markl+2][markr+1]>0)))
        {
            flag=1;
        }
        else
        {
            map0[markl][markr]=1;
            map0[markl+1][markr]=1;
            map0[markl+2][markr]=1;
            map0[markl][markr+1]=1;
        }
    }
    if(fl==5)
    {
        if(map0[markl][markr]>0||map0[markl][markr+1]>0||map0[markl][markr-1]>0||map0[markl-1][markr]>0||((map0[markl-1][markr-1]>0||map0[markl-2][markr]>0||map0[markl-1][markr+1]>0)&&
        (map0[markl-1][markr-1]>0||map0[markl][markr-2]>0)&&(map0[markl+1][markr]>0||map0[markl+1][markr+1]>0||map0[markl+1][markr-1]>0)&&(map0[markl][markr+2]>0||map0[markl-1][markr+1]>0)))
        {
            flag=1;
        }
        else
        {
            map0[markl][markr]=1;
            map0[markl][markr+1]=1;
            map0[markl][markr-1]=1;
            map0[markl-1][markr]=1;
        }
    }

}
void y()///旋转,把上一个旋转类型的位置清零，置为当前旋转类型
{
    if(fl==2)
    {
        if(yl==0)
        {
            if(map0[markl+1][markr]==0)
            {map0[markl-1][markr]=0;
            map0[markl+1][markr]=1;}
        }
        if(yl==1)
        {
            if(map0[markl][markr-1]==0)
            {map0[markl][markr+1]=0;
            map0[markl][markr-1]=1;}
        }
        if(yl==2)
        {
            if(map0[markl-1][markr]==0)
            {map0[markl+1][markr]=0;
            map0[markl-1][markr]=1;}
        }
        if(yl==3)
        {
            if(map0[markl][markr+1]==0)
            {map0[markl][markr-1]=0;
            map0[markl][markr+1]=1;}
        }
    }
    if(fl==4)
    {
        if(yl==0)
        {
            if(map0[markl+1][markr]==0&&map0[markl+2][markr]==0)
            {map0[markl][markr+2]=0;
            map0[markl-1][markr]=0;
            map0[markl+1][markr]=1;
            map0[markl+2][markr]=1;}
        }
        if(yl==1)
        {
            if(map0[markl][markr-1]==0&&map0[markl][markr-2]==0)
            {map0[markl][markr+1]=0;
            map0[markl+2][markr]=0;
            map0[markl][markr-1]=1;
            map0[markl][markr-2]=1;}
        }
        if(yl==2)
        {
            if(map0[markl-1][markr]==0&&map0[markl-2][markr]==0)
            {map0[markl][markr-2]=0;
            map0[markl+1][markr]=0;
            map0[markl-1][markr]=1;
            map0[markl-2][markr]=1;}
        }
        if(yl==3)
        {
            if(map0[markl][markr+1]==0&&map0[markl][markr+2]==0)
            {map0[markl-2][markr]=0;
            map0[markl][markr-1]=0;
            map0[markl][markr+1]=1;
            map0[markl][markr+2]=1;}
        }
    }
    if(fl==5)
    {
        if(yl==0)
        {
            if(map0[markl][markr+1]==0)
            {map0[markl+1][markr]=0;
            map0[markl][markr+1]=1;}
        }
        if(yl==1)
        {
            if(map0[markl+1][markr]==0)
            {map0[markl][markr-1]=0;
            map0[markl+1][markr]=1;}
        }
        if(yl==2)
        {
            if(map0[markl][markr-1]==0)
            {map0[markl-1][markr]=0;
            map0[markl][markr-1]=1;}
        }
        if(yl==3)
        {
            if(map0[markl-1][markr]==0)
            {map0[markl][markr+1]=0;
            map0[markl-1][markr]=1;}
        }
    }
    if(fl==3)
    {
        if(yl==0||yl==2)
        {
            if(map0[markl-1][markr]==0&&map0[markl+1][markr]==0)
            {map0[markl][markr-1]=0;
            map0[markl][markr+1]=0;
            map0[markl-1][markr]=1;
            map0[markl+1][markr]=1;}
        }
        if(yl==1||yl==3)
        {
            if(map0[markl][markr-1]==0&&map0[markl][markr+1]==0)
            {map0[markl][markr-1]=1;
            map0[markl][markr+1]=1;
            map0[markl-1][markr]=0;
            map0[markl+1][markr]=0;}
        }

    }
}
void caidan()
{
    if(cnt>=5)
    {cout<<"你的得分超过5分，获得2级称号："<<endl;
    cout<<"计科1804 小徐姑娘"<<endl;}
    if(cnt>=10)
    {
        cout<<"你的得分超过10分，获得3级称号："<<endl;
        cout<<"upc 生日牛逼徐"<<endl;
    }
    if(cnt>=15)
    {
        cout<<"你的得分超过15分，获得4级称号："<<endl;
        cout<<"China 第一酷女孩"<<endl;
    }
    if(cnt>=21)
    {
        cout<<"你的得分超过21分，获得至尊称号："<<endl;
        cout<<"戴着黑眼圈的翻墙之王！！！"<<endl;                                                                                                                                                                                                                                                     if(cnt>=50) cout<<"这是一个充满BUG的游戏，很感谢你能玩到这么高的分数。我愿意当你的骑士，一直保护你，公主殿下！"<<endl<<"万事如意，生日牛逼！！"<<endl;
    }

}
void move0()///移动,把移动前的位置置0，移动后的位置置1
{
    if(c=='a'||c=='A')
    {
        if(fl==1)
        {
            if(map0[markl][markr-1]==0&&map0[markl+1][markr-1]==0)
            {map0[markl][markr]=0;
            map0[markl+1][markr+1]=0;
            map0[markl+1][markr]=0;
            map0[markl][markr+1]=0;
            markr--;
            map0[markl][markr]=1;
            map0[markl+1][markr+1]=1;
            map0[markl+1][markr]=1;
            map0[markl][markr+1]=1;}
            if(map0[markl][markr-1]>0||map0[markl+1][markr-1]>0||markr==0)
            {
                map0[markl][markr]=2;
                map0[markl+1][markr+1]=2;
                map0[markl+1][markr]=2;
                map0[markl][markr+1]=2;
                flag0=1;
            }
        }
        if(fl==2)
        {
            if(yl==0)
            {
                if(map0[markl][markr-1]==0&&map0[markl+1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr+1]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr+1]=1;}
                if(map0[markl][markr-1]>0||map0[markl+1][markr-1]>0||markr==0)
                {
                    map0[markl][markr]=2;
                    map0[markl+1][markr]=2;
                    map0[markl][markr+1]=2;
                    flag0=1;
                }
            }
            if(yl==1)
            {
                if(map0[markl][markr-2]==0&&map0[markl+1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-1]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl][markr-2]>0||map0[markl+1][markr-1]>0||markr==1)
                {
                    map0[markl][markr]=2;
                    map0[markl+1][markr]=2;
                    map0[markl][markr-1]=2;
                    flag0=1;
                }

            }
            if(yl==2)
            {
                if(map0[markl][markr-2]==0&&map0[markl-1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr-1]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl-1][markr-1]>0||map0[markl][markr-2]>0||markr==1)
                {
                    map0[markl][markr]=2;
                    map0[markl-1][markr]=2;
                    map0[markl][markr-1]=2;
                    flag0=1;
                }

            }
            if(yl==3)
            {
                if(map0[markl][markr-1]==0&&map0[markl-1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr+1]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr+1]=1;}
                if(map0[markl][markr-1]>0||map0[markl-1][markr-1]>0||markr==0)
                {
                    map0[markl][markr]=2;
                    map0[markl-1][markr]=2;
                    map0[markl][markr+1]=2;
                    flag0=1;
                }
            }
        }
        if(fl==3)
        {
            if(yl==0||yl==2)
            {
                if(map0[markl][markr-1]==0&&map0[markl+1][markr-1]==0&&map0[markl-1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl-1][markr]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl-1][markr]=1;}
                if(map0[markl][markr-1]>0||markr==0||map0[markl-1][markr-1]>0||map0[markl+1][markr-1]>0)
                {
                    map0[markl][markr]=2;
                    map0[markl+1][markr]=2;
                    map0[markl-1][markr]=2;
                    flag0=1;
                }
            }
            if(yl==3||yl==1)
            {
                if(map0[markl][markr-2]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl][markr-1]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl][markr-2]>0||markr==1)
                {
                    map0[markl][markr]=2;
                    map0[markl][markr+1]=2;
                    map0[markl][markr-1]=2;
                    flag0=1;
                }
            }
        }
        if(fl==4)
        {
            if(yl==0)
            {
                if(map0[markl][markr-1]==0&&map0[markl+1][markr-1]==0&&map0[markl+2][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl+1][markr]=0;
                map0[markl+2][markr]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl+1][markr]=1;
                map0[markl+2][markr]=1;}
                if(map0[markl][markr-1]>0||markr==0||map0[markl+1][markr-1]>0||map0[markl+2][markr-1]>0)
                {
                    map0[markl][markr]=2;
                    map0[markl][markr+1]=2;
                    map0[markl+1][markr]=2;
                    map0[markl+2][markr]=2;
                    flag0=1;
                }
            }
            if(yl==1)
            {
                if(map0[markl][markr-3]==0&&map0[markl+1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-2]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-2]=1;}
                if(map0[markl+1][markr-1]>0||markr==2||map0[markl][markr-3]>0)
                {
                    map0[markl][markr]=2;
                    map0[markl][markr-1]=2;
                    map0[markl+1][markr]=2;
                    map0[markl][markr-2]=2;
                    flag0=1;
                }
            }
            if(yl==2)
            {
                if(map0[markl][markr-2]==0&&map0[markl-1][markr-1]==0&&map0[markl-2][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl-1][markr]=0;
                map0[markl-2][markr]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl-1][markr]=1;
                map0[markl-2][markr]=1;}
                if(map0[markl][markr-2]>0||markr==1||map0[markl-1][markr-1]>0||map0[markl-2][markr-1]>0)
                {
                    map0[markl][markr]=2;
                    map0[markl][markr-1]=2;
                    map0[markl-1][markr]=2;
                    map0[markl-2][markr]=2;
                    flag0=1;
                }
            }
            if(yl==3)
            {
                if(map0[markl][markr-1]==0&&map0[markl-1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr+2]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr+2]=1;}
                if(map0[markl][markr-1]>0||markr==0||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=2;
                    map0[markl][markr+1]=2;
                    map0[markl-1][markr]=2;
                    map0[markl][markr+2]=2;
                    flag0=1;
                }
            }
        }
        if(fl==5)
        {
            if(yl==0)
            {
                if(map0[markl][markr-2]==0&&map0[markl-1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr-1]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl][markr-2]>0||markr==1||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=2;
                    map0[markl][markr+1]=2;
                    map0[markl-1][markr]=2;
                    map0[markl][markr-1]=2;
                    flag0=1;
                }
            }
            if(yl==1)
            {
                if(map0[markl][markr-1]==0&&map0[markl+1][markr-1]==0&&map0[markl-1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr+1]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl+1][markr]=1;}
                if(map0[markl][markr-1]>0||markr==0||map0[markl+1][markr-1]>0||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=2;
                    map0[markl][markr+1]=2;
                    map0[markl-1][markr]=2;
                    map0[markl+1][markr]=2;
                    flag0=1;
                }
            }
            if(yl==2)
            {
                if(map0[markl][markr-2]==0&&map0[markl+1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-1]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl][markr-2]>0||markr==1||map0[markl+1][markr-1]>0)
                {
                    map0[markl][markr]=2;
                    map0[markl][markr+1]=2;
                    map0[markl+1][markr]=2;
                    map0[markl][markr-1]=2;
                    flag0=1;
                }
            }
            if(yl==3)
            {
                if(map0[markl][markr-2]==0&&map0[markl+1][markr-1]==0&&map0[markl-1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl+1][markr]=0;
                map0[markl-1][markr]=0;
                markr--;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl+1][markr]=1;
                map0[markl-1][markr]=1;}
                if(map0[markl][markr-2]>0||markr==1||map0[markl+1][markr-1]>0||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=2;
                    map0[markl][markr-1]=2;
                    map0[markl+1][markr]=2;
                    map0[markl+1][markr]=2;
                    flag0=1;
                }
            }
        }
    }
    if(c=='s'||c=='S')
    {
        if(fl==1)
        {
            if(map0[markl+2][markr]==0&&map0[markl+2][markr+1]==0)
            {map0[markl][markr]=0;
            map0[markl+1][markr+1]=0;
            map0[markl+1][markr]=0;
            map0[markl][markr+1]=0;
            markl++;
            map0[markl][markr]=1;
            map0[markl+1][markr+1]=1;
            map0[markl+1][markr]=1;
            map0[markl][markr+1]=1;}
            if(map0[markl+2][markr]>0||markl==8||map0[markl+2][markr+1]>0)
            {
                map0[markl][markr]=5;
                map0[markl+1][markr+1]=5;
                map0[markl+1][markr]=5;
                map0[markl][markr+1]=5;
                flag0=1;
            }
        }
        if(fl==2)
        {
            if(yl==0)
            {
                if(map0[markl+2][markr]==0&&map0[markl+1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr+1]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr+1]=1;}
                if(map0[markl+2][markr]>0||markl==8||map0[markl+1][markr+1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl+1][markr]=5;
                    map0[markl][markr+1]=5;
                    flag0=1;
                }
            }
            if(yl==1)
            {
                if(map0[markl+1][markr-1]==0&&map0[markl+2][markr]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-1]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl+2][markr]>0||markl==8||map0[markl+1][markr-1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl+1][markr]=5;
                    map0[markl][markr-1]=5;
                    flag0=1;
                }

            }
            if(yl==2)
            {
                if(map0[markl+1][markr-1]==0&&map0[markl+1][markr]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr-1]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl+1][markr]>0||markl==9||map0[markl+1][markr-1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl-1][markr]=5;
                    map0[markl][markr-1]=5;
                    flag0=1;
                }
            }
            if(yl==3)
            {
                if(map0[markl+1][markr]==0&&map0[markl+1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr+1]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr+1]=1;}
                if(map0[markl+1][markr]>0||markl==9||map0[markl+1][markr+1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl-1][markr]=5;
                    map0[markl][markr+1]=5;
                    flag0=1;
                }
            }
        }
        if(fl==3)
        {
            if(yl==0||yl==2)
            {
                if(map0[markl+2][markr]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl-1][markr]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl-1][markr]=1;}
                if(map0[markl+2][markr]>0||markl==8)
                {
                    map0[markl][markr]=5;
                    map0[markl+1][markr]=5;
                    map0[markl-1][markr]=5;
                    flag0=1;
                }
            }
            if(yl==3||yl==1)
            {
                if(map0[markl+1][markr-1]==0&&map0[markl+1][markr+1]==0&&map0[markl+1][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl][markr-1]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl+1][markr]>0||markl==9||map0[markl+1][markr-1]>0||map0[markl+1][markr+1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl][markr+1]=5;
                    map0[markl][markr-1]=5;
                    flag0=1;
                }
            }
        }
        if(fl==4)
        {
            if(yl==0)
            {
                if(map0[markl+3][markr]==0&&map0[markl+1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl+1][markr]=0;
                map0[markl+2][markr]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl+1][markr]=1;
                map0[markl+2][markr]=1;}
                if(map0[markl+3][markr]>0||markl==7||map0[markl+1][markr+1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl][markr+1]=5;
                    map0[markl+1][markr]=5;
                    map0[markl+2][markr]=5;
                    flag0=1;
                }
            }
            if(yl==1)
            {
                if(map0[markl+1][markr-2]==0&&map0[markl+1][markr-1]==0&&map0[markl+2][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-2]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-2]=1;}
                if(map0[markl+2][markr]>0||markl==8||map0[markl+1][markr-1]>0||map0[markl+1][markr-2]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl][markr-1]=5;
                    map0[markl+1][markr]=5;
                    map0[markl][markr-2]=5;
                    flag0=1;
                }
            }
            if(yl==2)
            {
                if(map0[markl+1][markr-1]==0&&map0[markl+1][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl-1][markr]=0;
                map0[markl-2][markr]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl-1][markr]=1;
                map0[markl-2][markr]=1;}
                if(map0[markl+1][markr]>0||markl==9||map0[markl+1][markr-1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl][markr-1]=5;
                    map0[markl-1][markr]=5;
                    map0[markl-2][markr]=5;
                    flag0=1;
                }
            }
            if(yl==3)
            {
                if(map0[markl+1][markr+2]==0&&map0[markl+1][markr+1]==0&&map0[markl+1][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr+2]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr+2]=1;}
                if(map0[markl+1][markr]>0||markl==9||map0[markl+1][markr+1]>0||map0[markl+1][markr+2]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl][markr+1]=5;
                    map0[markl-1][markr]=5;
                    map0[markl][markr+2]=5;
                    flag0=1;
                }
            }
        }
        if(fl==5)
        {
            if(yl==0)
            {
                if(map0[markl+1][markr-1]==0&&map0[markl+1][markr+1]==0&&map0[markl+1][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr-1]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl+1][markr]>0||markl==9||map0[markl+1][markr+1]>0||map0[markl+1][markr-1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl][markr+1]=5;
                    map0[markl-1][markr]=5;
                    map0[markl][markr-1]=5;
                    flag0=1;
                }
            }
            if(yl==1)
            {
                if(map0[markl+2][markr]==0&&map0[markl+1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr+1]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl+1][markr]=1;}
                if(map0[markl+2][markr]>0||markl==8||map0[markl+1][markr+1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl][markr+1]=5;
                    map0[markl+1][markr]=5;
                    map0[markl-1][markr]=5;
                    flag0=1;
                }
            }
            if(yl==2)
            {
                if(map0[markl+1][markr-1]==0&&map0[markl+1][markr+1]==0&&map0[markl+2][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-1]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl+2][markr]>0||markl==8||map0[markl+1][markr+1]>0||map0[markl+1][markr-1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl][markr+1]=5;
                    map0[markl+1][markr]=5;
                    map0[markl][markr-1]=5;
                    flag0=1;
                }
            }
            if(yl==3)
            {
                if(map0[markl+1][markr-1]==0&&map0[markl+2][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl+1][markr]=0;
                map0[markl-1][markr]=0;
                markl++;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl+1][markr]=1;
                map0[markl-1][markr]=1;}
                if(map0[markl+2][markr]>0||markl==8||map0[markl+1][markr-1]>0)
                {
                    map0[markl][markr]=5;
                    map0[markl][markr-1]=5;
                    map0[markl+1][markr]=5;
                    map0[markl-1][markr]=5;
                    flag0=1;
                }
            }
        }
    }
    if(c=='d'||c=='D')
    {
        if(fl==1)
        {
            if(map0[markl][markr+2]==0&&map0[markl+1][markr+2]==0)
            {map0[markl][markr]=0;
            map0[markl+1][markr+1]=0;
            map0[markl+1][markr]=0;
            map0[markl][markr+1]=0;
            markr++;
            map0[markl][markr]=1;
            map0[markl+1][markr+1]=1;
            map0[markl+1][markr]=1;
            map0[markl][markr+1]=1;}
            if(map0[markl][markr+2]>0||markr==8||map0[markl+1][markr+2]>0)
            {
                map0[markl][markr]=4;
                map0[markl+1][markr+1]=4;
                map0[markl+1][markr]=4;
                map0[markl][markr+1]=4;
                flag0=1;
            }
        }
        if(fl==2)
        {
            if(yl==0)
            {
                if(map0[markl][markr+2]==0&&map0[markl+1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr+1]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr+1]=1;}
                if(map0[markl][markr+2]>0||markr==8||map0[markl+1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl+1][markr]=4;
                    map0[markl][markr+1]=4;
                    flag0=1;
                }

            }
            if(yl==1)
            {
                if(map0[markl][markr+1]==0&&map0[markl+1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-1]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl][markr+1]>0||markr==9||map0[markl+1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl+1][markr]=4;
                    map0[markl][markr-1]=4;
                    flag0=1;
                }


            }
            if(yl==2)
            {
                if(map0[markl][markr+1]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr-1]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl][markr+1]>0||markr==9||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl-1][markr]=4;
                    map0[markl][markr-1]=4;
                    flag0=1;
                }

            }
            if(yl==3)
            {
                if(map0[markl][markr+2]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr+1]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr+1]=1;}
                if(map0[markl][markr+2]>0||markr==8||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl-1][markr]=4;
                    map0[markl][markr+1]=4;
                    flag0=1;
                }
            }
        }
        if(fl==3)
        {
            if(yl==0||yl==2)
            {
                if(map0[markl][markr+1]==0&&map0[markl+1][markr+1]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl-1][markr]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl-1][markr]=1;}
                if(map0[markl][markr+1]>0||markr==9||map0[markl+1][markr+1]>0||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl+1][markr]=4;
                    map0[markl-1][markr]=4;
                    flag0=1;
                }

            }
            if(yl==3||yl==1)
            {
                if(map0[markl][markr+2]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl][markr-1]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl][markr+2]>0||markr==8)
                {
                    map0[markl][markr]=4;
                    map0[markl][markr-1]=4;
                    map0[markl][markr+1]=4;
                    flag0=1;
                }

            }
        }
        if(fl==4)
        {
            if(yl==0)
            {
                if(map0[markl][markr+2]==0&&map0[markl+1][markr+1]==0&&map0[markl+2][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl+1][markr]=0;
                map0[markl+2][markr]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl+1][markr]=1;
                map0[markl+2][markr]=1;}
                if(map0[markl][markr+2]>0||markr==8||map0[markl+1][markr+1]>0||map0[markl+2][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl+1][markr]=4;
                    map0[markl][markr+1]=4;
                    map0[markl+2][markr]=4;
                    flag0=1;
                }

            }
            if(yl==1)
            {
                if(map0[markl][markr+1]==0&&map0[markl+1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-2]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-2]=1;}
                if(map0[markl][markr+1]>0||markr==9||map0[markl+1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl+1][markr]=4;
                    map0[markl][markr-1]=4;
                    map0[markl][markr-2]=4;
                    flag0=1;
                }

            }
            if(yl==2)
            {
                if(map0[markl][markr+1]==0&&map0[markl-1][markr+1]==0&&map0[markl-2][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl-1][markr]=0;
                map0[markl-2][markr]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl-1][markr]=1;
                map0[markl-2][markr]=1;}
                if(map0[markl][markr+1]>0||markr==9||map0[markl-1][markr+1]>0||map0[markl-2][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl-1][markr]=4;
                    map0[markl][markr-1]=4;
                    map0[markl-2][markr]=4;
                    flag0=1;
                }

            }
            if(yl==3)
            {
                if(map0[markl][markr+3]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr+2]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr+2]=1;}
                if(map0[markl][markr+3]>0||markr==7||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl][markr+2]=4;
                    map0[markl][markr+1]=4;
                    map0[markl-1][markr]=4;
                    flag0=1;
                }

            }
        }
        if(fl==5)
        {
            if(yl==0)
            {
                if(map0[markl][markr+2]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr-1]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl][markr+2]>0||markr==8||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl][markr-1]=4;
                    map0[markl][markr+1]=4;
                    map0[markl-1][markr]=4;
                    flag0=1;
                }

            }
            if(yl==1)
            {
                if(map0[markl][markr+2]==0&&map0[markl-1][markr+1]==0&&map0[markl+1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr+1]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl+1][markr]=1;}
                if(map0[markl][markr+2]>0||markr==8||map0[markl+1][markr+1]>0||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl+1][markr]=4;
                    map0[markl][markr+1]=4;
                    map0[markl-1][markr]=4;
                    flag0=1;
                }

            }
            if(yl==2)
            {
                if(map0[markl][markr+2]==0&&map0[markl+1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-1]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl][markr+2]>0||markr==8||map0[markl+1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl+1][markr]=4;
                    map0[markl][markr+1]=4;
                    map0[markl][markr-1]=4;
                    flag0=1;
                }

            }
            if(yl==3)
            {
                if(map0[markl][markr+1]==0&&map0[markl+1][markr+1]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl+1][markr]=0;
                map0[markl-1][markr]=0;
                markr++;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl+1][markr]=1;
                map0[markl-1][markr]=1;}
                if(map0[markl][markr+1]>0||markr==9||map0[markl+1][markr+1]>0||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=4;
                    map0[markl+1][markr]=4;
                    map0[markl][markr-1]=4;
                    map0[markl-1][markr]=4;
                    flag0=1;
                }

            }
        }
    }
    if(c=='w'||c=='W')
    {
        if(fl==1)
        {
            if(map0[markl-1][markr]==0&&map0[markl-1][markr+1]==0)
            {map0[markl][markr]=0;
            map0[markl+1][markr+1]=0;
            map0[markl+1][markr]=0;
            map0[markl][markr+1]=0;
            markl--;
            map0[markl][markr]=1;
            map0[markl+1][markr+1]=1;
            map0[markl+1][markr]=1;
            map0[markl][markr+1]=1;}
            if(map0[markl-1][markr]>0||markl==0||map0[markl-1][markr+1]>0)
            {
                map0[markl][markr]=3;
                map0[markl+1][markr]=3;
                map0[markl][markr+1]=3;
                map0[markl+1][markr+1]=3;
                flag0=1;
            }

        }
        if(fl==2)
        {
            if(yl==0)
            {
                if(map0[markl-1][markr]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr+1]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr+1]=1;}
                if(map0[markl-1][markr]>0||markl==0||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl+1][markr]=3;
                    map0[markl][markr+1]=3;
                    flag0=1;
                }

            }
            if(yl==1)
            {
                if(map0[markl-1][markr]==0&&map0[markl-1][markr-1]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-1]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl-1][markr]>0||markl==0||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl+1][markr]=3;
                    map0[markl][markr-1]=3;
                    flag0=1;
                }

            }
            if(yl==2)
            {
                if(map0[markl-1][markr-1]==0&&map0[markl-2][markr]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr-1]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl-2][markr]>0||markl==1||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl-1][markr]=3;
                    map0[markl][markr-1]=3;
                    flag0=1;
                }

            }
            if(yl==3)
            {
                if(map0[markl-2][markr]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr+1]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr+1]=1;}
                if(map0[markl-2][markr]>0||markl==1||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl-1][markr]=3;
                    map0[markl][markr+1]=3;
                    flag0=1;
                }

            }
        }
        if(fl==3)
        {
            if(yl==0||yl==2)
            {
                if(map0[markl-2][markr]==0)
                {map0[markl][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl-1][markr]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl+1][markr]=1;
                map0[markl-1][markr]=1;}
                if(map0[markl-2][markr]>0||markl==1)
                {
                    map0[markl][markr]=3;
                    map0[markl+1][markr]=3;
                    map0[markl-1][markr]=3;
                    flag0=1;
                }

            }
            if(yl==3||yl==1)
            {
                if(map0[markl-1][markr-1]==0&&map0[markl-1][markr+1]==0&&map0[markl-1][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl][markr-1]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl-1][markr]>0||markl==0||map0[markl-1][markr+1]>0||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl][markr-1]=3;
                    map0[markl][markr+1]=3;
                    flag0=1;
                }
            }
        }
        if(fl==4)
        {
            if(yl==0)
            {
                if(map0[markl-1][markr]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl+1][markr]=0;
                map0[markl+2][markr]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl+1][markr]=1;
                map0[markl+2][markr]=1;}
                if(map0[markl-1][markr]>0||markl==0||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl+1][markr]=3;
                    map0[markl][markr+1]=3;
                    map0[markl+2][markr]=3;
                    flag0=1;
                }

            }
            if(yl==1)
            {
                if(map0[markl-1][markr-2]==0&&map0[markl-1][markr-1]==0&&map0[markl-1][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-2]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-2]=1;}
                if(map0[markl-1][markr]>0||markl==0||map0[markl-1][markr-1]>0||map0[markl-1][markr-2]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl+1][markr]=3;
                    map0[markl][markr-1]=3;
                    map0[markl][markr-2]=3;
                    flag0=1;
                }

            }
            if(yl==2)
            {
                if(map0[markl-1][markr-1]==0&&map0[markl-3][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl-1][markr]=0;
                map0[markl-2][markr]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl-1][markr]=1;
                map0[markl-2][markr]=1;}
                if(map0[markl-3][markr]>0||markl==2||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl-1][markr]=3;
                    map0[markl][markr-1]=3;
                    map0[markl-2][markr]=3;
                    flag0=1;
                }

            }
            if(yl==3)
            {
                if(map0[markl-2][markr]==0&&map0[markl-1][markr+1]==0&&map0[markl-1][markr+2]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr+2]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr+2]=1;}
                if(map0[markl-2][markr]>0||markl==1||map0[markl-1][markr+1]>0||map0[markl-1][markr+2]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl-1][markr]=3;
                    map0[markl][markr+1]=3;
                    map0[markl][markr+2]=3;
                    flag0=1;
                }

            }
        }
        if(fl==5)
        {
            if(yl==0)
            {
                if(map0[markl-1][markr-1]==0&&map0[markl-2][markr]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl-1][markr]=0;
                map0[markl][markr-1]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl-2][markr]>0||markl==1||map0[markl-1][markr+1]>0||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl-1][markr]=3;
                    map0[markl][markr+1]=3;
                    map0[markl][markr-1]=3;
                    flag0=1;
                }

            }
            if(yl==1)
            {
                if(map0[markl-2][markr]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl-1][markr]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr+1]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl-1][markr]=1;
                map0[markl+1][markr]=1;}
                if(map0[markl-2][markr]>0||markl==1||map0[markl-1][markr+1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl+1][markr]=3;
                    map0[markl][markr+1]=3;
                    map0[markl-1][markr]=3;
                    flag0=1;
                }

            }
            if(yl==2)
            {
                if(map0[markl-1][markr-1]==0&&map0[markl-1][markr]==0&&map0[markl-1][markr+1]==0)
                {map0[markl][markr]=0;
                map0[markl][markr+1]=0;
                map0[markl+1][markr]=0;
                map0[markl][markr-1]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl][markr+1]=1;
                map0[markl+1][markr]=1;
                map0[markl][markr-1]=1;}
                if(map0[markl-1][markr]>0||markl==0||map0[markl-1][markr+1]>0||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl+1][markr]=3;
                    map0[markl][markr+1]=3;
                    map0[markl][markr-1]=3;
                    flag0=1;
                }

            }
            if(yl==3)
            {
                if(map0[markl-1][markr-1]==0&&map0[markl-2][markr]==0)
                {map0[markl][markr]=0;
                map0[markl][markr-1]=0;
                map0[markl+1][markr]=0;
                map0[markl-1][markr]=0;
                markl--;
                map0[markl][markr]=1;
                map0[markl][markr-1]=1;
                map0[markl+1][markr]=1;
                map0[markl-1][markr]=1;}
                if(map0[markl-2][markr]>0||markl==1||map0[markl-1][markr-1]>0)
                {
                    map0[markl][markr]=3;
                    map0[markl+1][markr]=3;
                    map0[markl][markr-1]=3;
                    map0[markl-1][markr]=3;
                    flag0=1;
                }

            }
        }
    }

}
void xiaochu()///消除
{
    int cntx=0;///记录每行格子数
    int cnty=0;///记录消除的行数
    ///消除左边
    for(int i=0;i<10;i++)
    {
        for(int j=1;j<=8;j++)
        {
            if(map0[j][i]==2) cntx++;
        }
        if(cntx==8)
        {
            for(int j=1;j<=8;j++)
            {
                map0[j][i]=0;
            }
            cnt++;
            cnty++;
        }
        cntx=0;
    }
    for(int i=1;i<=8;i++)
    {
        for(int j=0;j<10;j++)
        {
            if(map0[i][j]==2&&cnty!=0)
            {
                map0[i][j-cnty]=2;
                map0[i][j]=0;
            }
        }
    }
    cntx=0;cnty=0;
    ///消除上边
    for(int i=0;i<10;i++)
    {
        for(int j=1;j<=8;j++)
        {
            if(map0[i][j]==3) cntx++;
        }
        if(cntx==8)
        {
            for(int j=1;j<=8;j++)
            {
                map0[i][j]=0;
            }
            cnt++;
            cnty++;
        }
        cntx=0;
    }
    for(int i=1;i<=8;i++)
    {
        for(int j=0;j<10;j++)
        {
            if(map0[j][i]==3&&cnty!=0)
            {
                map0[j-cnty][i]=3;
                map0[j][i]=0;
            }

        }
    }
    cntx=0;cnty=0;
    ///消除右边
    for(int i=0;i<10;i++)
    {
        for(int j=1;j<=8;j++)
        {
            if(map0[j][i]==4) cntx++;
        }
        if(cntx==8)
        {
            for(int j=1;j<=8;j++)
            {
                map0[j][i]=0;
            }
            cnt++;
            cnty++;
        }
        cntx=0;
    }
    for(int i=1;i<=8;i++)
    {
        for(int j=0;j<10;j++)
        {
            if(map0[i][j]==4&&cnty!=0)
            {
                map0[i][j+cnty]=4;
                map0[i][j]=0;
            }
        }
    }
    cntx=0;cnty=0;
    ///消除下边
    for(int i=0;i<10;i++)
    {
        for(int j=1;j<=8;j++)
        {
            if(map0[i][j]==5) cntx++;
        }
        if(cntx==8)
        {
            for(int j=1;j<=8;j++)
            {
                map0[i][j]=0;
            }
            cnt++;
            cnty++;
        }
        cntx=0;
    }
    for(int i=1;i<=8;i++)
    {
        for(int j=0;j<10;j++)
        {
            if(map0[j][i]==5&&cnty!=0)
            {
                map0[j+cnty][i]=5;
                map0[j][i]=0;
            }

        }
    }

}
void run()///运行游戏
{
    creat();
    system("cls");
    print();
    xiaochu();
    system("cls");
    print();
    if(cnt>Max) flag=2;
    while(1)
    {
        if(flag) break;
        cin>>c;
        if(c=='y'||c=='Y') {yl=(yl+1)%4;y();}
        if(c=='a'||c=='A'||c=='s'||c=='S'||c=='d'||c=='D'||c=='w'||c=='W')
            move0();
        system("cls");
        print();
        xiaochu();
        system("cls");
        print();
        if(cnt>Max) flag=2;
        if(flag0) break;

    }
    yl=0;
    flag0=0;
}
int main()
{
    srand(time(0));
    while(!flag)
    {run();}
    if(flag==1)
    {
        system("cls");
        cout<<"你失败了，你的得分为："<<cnt<<endl;
    }
    if(flag==2)
    {
        system("cls");
        cout<<"恭喜你顺利通过，获得一级称号："<<endl;
        cout<<"03 徐子怡"<<endl;
    }
    caidan();
    cout << "Hello XiaoXu!" << endl;
    return 0;
}
